### PR TITLE
A few small updates

### LINKED ISSUE #4: Remove unused .repo-list class?
In the CSS there are `.repo-list` styles that are not being used on the demo site. Is it ok to delete them or do you have plans to use them?

### PR DESCRIPTION
**Pull request by Scotchester**
I had this work done and figured it was worth committing it before I move on to setting up a build branch.

Closes #4.

### CODE REVIEW

**Comment by ascott1** [comment]
I like adding the dynamically generated repo list... the formatting changes all seem to be personal preference though (and cause a merge conflict?)

**Comment by Scotchester** [comment]
Updated to remediate my mistake about the tab length standard (or lack thereof). Apologies!

**Comment by ascott1** [comment]
Thanks @Scotchester. Also, I see the issue. It looks like you hadn't pulled down from upstream recently (I see the original DOCter url in your config file). Mind doing so and re-pushing? That should fix merge conflicts locally. Thanks again!

**Comment by Scotchester** [comment]
Oy, sorry for the brain fart. Should be good to go now!

**Comment by ascott1** [comment]
:boom:

**Pull request merged**
