### PR TITLE
Pj bea patch 1

### PR DESCRIPTION
**Pull request by pjux-old**
Error 1

### CODE REVIEW

**Comment by pjux-old** [comment]
Looks legit.

**Comment by pjux-old** [comment]
Nah

**Comment by ascott1** [comment]
@pj-bea If you'd like help getting DOCter working for your own projects, feel free to reach out! Best of luck

**Comment by pjux-old** [comment]
@ascott1 Thanks, I think I'm doing it right. Can you take a look? Just trying to figure it out over here.

**Comment by ascott1** [comment]
https://pj-bea.github.io/DOCter/ looks great to me! (note that you don't need to list index.html in the url). Feel free to reach me through issues in this repo if you ever have questions or difficulty.

**Pull request closed without merging**
